# Generated by Django 3.1.1 on 2021-03-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
