# Generated by Django 3.1.1 on 2021-03-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_feedback_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='updated',
        ),
    ]
