# Generated by Django 3.1.1 on 2021-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
