# Generated by Django 3.1.1 on 2021-03-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='funfact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='quote1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='quote2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='quote3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
