# Generated by Django 3.1.1 on 2021-03-30 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0002_auto_20210330_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
