# Generated by Django 3.1.1 on 2021-04-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_auto_20210404_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='answers', to='quizes.Answer'),
        ),
    ]
